const Deck = [
    {
      order: 0,
      title: 'El Loco',
      imageSrc: 'img/maj00.jpg',
      description: `Una persona inocente y buena al inicio de un viaje.`,
      tags: ['mayor'],
    },
    {
      order: 1,
      title: 'El Mago',
      imageSrc: 'img/maj01.jpg',
      description: `El maestro que lo presenta ante un potencial ilimitado.`,
      tags: ['mayor'],
    },
    {
      order: 2,
      title: 'La Sacerdotisa',
      imageSrc: 'img/maj02.jpg',
      description: `Ella es nuestra intuición, los misterios del espíritu.`,
      tags: ['mayor'],
    },
    {
      order: 3,
      title: 'La Emperatriz',
      imageSrc: 'img/maj03.jpg',
      description: `Representa la creatividad, la fertilidad y a la Naturaleza.`,
      tags: ['mayor'],
    },
    {
      order: 4,
      title: 'El Emperador',
      imageSrc: 'img/maj04.jpg',
      description: `Representa el poder, la estructura y el control.`,
      tags: ['mayor'],
    },
    {
      order: 5,
      title: 'El Sacerdote',
      imageSrc: 'img/maj05.jpg',
      description: `La estructura religiosa tradicional, el guía espiritual.`,
      tags: ['mayor'],
    },
    {
      order: 6,
      title: 'Los Amantes',
      imageSrc: 'img/maj06.jpg',
      description: `Lecciones de amor, incluyendo el amor a sí mismo.`,
      tags: ['mayor'],
    },
    {
      order: 7,
      title: 'El Carro',
      imageSrc: 'img/maj07.jpg',
      description: `Conflictos o decisiones. Posible viaje.`,
      tags: ['mayor'],
    },
    {
      order: 8,
      title: 'La Fuerza',
      imageSrc: 'img/maj08.jpg',
      description: `La fuerza que necesitamos para enfrentar a los problemas de la vida.`,
      tags: ['mayor'],
    },
    {
      order: 9,
      title: 'El Ermitaño',
      imageSrc: 'img/maj09.jpg',
      description: `La solitaria búsqueda de la Verdad.`,
      tags: ['mayor'],
    },
    {
      order: 10,
      title: 'La Rueda de la Fortuna',
      imageSrc: 'img/maj10.jpg',
      description: `Un cambio de suerte como el giro de una rueda.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'La Justicia',
      imageSrc: 'img/maj11.jpg',
      description: `La capacidad de considerar los hechos y realizar buenos juicios.`,
      tags: ['mayor'],
    },
    {
      order: 12,
      title: 'El Ahorcado',
      imageSrc: 'img/maj12.jpg',
      description: `Sacrificio de partes propias para un bien mayor.`,
      tags: ['mayor'],
    },
    {
      order: 13,
      title: 'La Muerte',
      imageSrc: 'img/maj13.jpg',
      description: `Un final o cambio, muerte metafórica.`,
      tags: ['mayor'],
    },
    {
      order: 14,
      title: 'La Tolerancia',
      imageSrc: 'img/maj14.jpg',
      description: `Balance interno o emocional.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'El Demonio',
      imageSrc: 'img/maj15.jpg',
      description: `El infierno y el sufrimiento que creamos en nuestra vida.`,
      tags: ['mayor'],
    },
    {
      order: 16,
      title: 'La Torre',
      imageSrc: 'img/maj16.jpg',
      description: `Destrucción de una estructura en la vida.`,
      tags: ['mayor'],
    },
    {
      order: 17,
      title: 'La Estrella',
      imageSrc: 'img/maj17.jpg',
      description: `El regalo de nuestro propio destino.`,
      tags: ['mayor'],
    },
    {
      order: 18,
      title: 'La Luna',
      imageSrc: 'img/maj18.jpg',
      description: `Ilusión o lo que no vemos.`,
      tags: ['mayor'],
    },
    {
      order: 19,
      title: 'El Sol',
      imageSrc: 'img/maj19.jpg',
      description: `Alegría y brillo y prosperidad.`,
      tags: ['mayor'],
    },
    {
      order: 20,
      title: 'El Juicio',
      imageSrc: 'img/maj20.jpg',
      description: `Pago de viejas deudas para un nuevo inicio.`,
      tags: ['mayor'],
    },
    {
      order: 21,
      title: 'El Mundo',
      imageSrc: 'img/maj21.jpg',
      description: `Un círculo que representa que el ciclo está completo.`,
      tags: ['mayor'],
    },
  ];

export default Deck;