const Deck = [
    {
      order: 0,
      title: 'El Loco',
      imageSrc: 'img/maj00.jpg',
      description: `Una persona inocente y buena al inicio de un viaje.`,
      tags: ['mayor'],
    },
    {
      order: 1,
      title: 'El Mago',
      imageSrc: 'img/maj01.jpg',
      description: `El maestro que lo presenta ante un potencial ilimitado.`,
      tags: ['mayor'],
    },
    {
      order: 2,
      title: 'La Sacerdotisa',
      imageSrc: 'img/maj02.jpg',
      description: `Ella es nuestra intuición, los misterios del espíritu.`,
      tags: ['mayor'],
    },
    {
      order: 3,
      title: 'La Emperatriz',
      imageSrc: 'img/maj03.jpg',
      description: `Representa la creatividad, la fertilidad y a la Naturaleza.`,
      tags: ['mayor'],
    },
    {
      order: 4,
      title: 'El Emperador',
      imageSrc: 'img/maj04.jpg',
      description: `Representa el poder, la estructura y el control.`,
      tags: ['mayor'],
    },
    {
      order: 5,
      title: 'El Sacerdote',
      imageSrc: 'img/maj05.jpg',
      description: `La estructura religiosa tradicional, el guía espiritual.`,
      tags: ['mayor'],
    },
    {
      order: 6,
      title: 'Los Amantes',
      imageSrc: 'img/maj06.jpg',
      description: `Lecciones de amor, incluyendo el amor a sí mismo.`,
      tags: ['mayor'],
    },
    {
      order: 7,
      title: 'El Carro',
      imageSrc: 'img/maj07.jpg',
      description: `Conflictos o decisiones. Posible viaje.`,
      tags: ['mayor'],
    },
    {
      order: 8,
      title: 'La Fuerza',
      imageSrc: 'img/maj08.jpg',
      description: `La fuerza que necesitamos para enfrentar a los problemas de la vida.`,
      tags: ['mayor'],
    },
    {
      order: 9,
      title: 'El Ermitaño',
      imageSrc: 'img/maj09.jpg',
      description: `La solitaria búsqueda de la Verdad.`,
      tags: ['mayor'],
    },
    {
      order: 10,
      title: 'La Rueda de la Fortuna',
      imageSrc: 'img/maj10.jpg',
      description: `Un cambio de suerte como el giro de una rueda.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'La Justicia',
      imageSrc: 'img/maj11.jpg',
      description: `La capacidad de considerar los hechos y realizar buenos juicios.`,
      tags: ['mayor'],
    },
    {
      order: 12,
      title: 'El Ahorcado',
      imageSrc: 'img/maj12.jpg',
      description: `Sacrificio de partes propias para un bien mayor.`,
      tags: ['mayor'],
    },
    {
      order: 13,
      title: 'La Muerte',
      imageSrc: 'img/maj13.jpg',
      description: `Un final o cambio, muerte metafórica.`,
      tags: ['mayor'],
    },
    {
      order: 14,
      title: 'La Tolerancia',
      imageSrc: 'img/maj14.jpg',
      description: `Balance interno o emocional.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'El Demonio',
      imageSrc: 'img/maj15.jpg',
      description: `El infierno y el sufrimiento que creamos en nuestra vida.`,
      tags: ['mayor'],
    },
    {
      order: 16,
      title: 'La Torre',
      imageSrc: 'img/maj16.jpg',
      description: `Destrucción de una estructura en la vida.`,
      tags: ['mayor'],
    },
    {
      order: 17,
      title: 'La Estrella',
      imageSrc: 'img/maj17.jpg',
      description: `El regalo de nuestro propio destino.`,
      tags: ['mayor'],
    },
    {
      order: 18,
      title: 'La Luna',
      imageSrc: 'img/maj18.jpg',
      description: `Ilusión o lo que no vemos.`,
      tags: ['mayor'],
    },
    {
      order: 19,
      title: 'El Sol',
      imageSrc: 'img/maj19.jpg',
      description: `Alegría y brillo y prosperidad.`,
      tags: ['mayor'],
    },
    {
      order: 20,
      title: 'El Juicio',
      imageSrc: 'img/maj20.jpg',
      description: `Pago de viejas deudas para un nuevo inicio.`,
      tags: ['mayor'],
    },
    {
      order: 21,
      title: 'El Mundo',
      imageSrc: 'img/maj21.jpg',
      description: `Un círculo que representa que el ciclo está completo.`,
      tags: ['mayor'],
    },

    {
      order: 1,
      title: 'As de Bastos',
      imageSrc: 'img/wands01.jpg',
      description: `El inicio de un nuevo proyecto creativo o energía creativa que empieza a ser llevada hacia otro proyecto.`,
      tags: ['bastos'],
    },
    {
      order: 2,
      title: '2 de Bastos',
      imageSrc: 'img/wands02.jpg',
      description: `Energía creativa que sólo busca ser liberada para traer buenos resultados.`,
      tags: ['bastos'],
    },
    {
      order: 3,
      title: '3 de Bastos',
      imageSrc: 'img/wands03.jpg',
      description: `Buenos resultados de la energía que invirtió, que vendrá de regreso de una manera positiva.`,
      tags: ['bastos'],
    },
    {
      order: 4,
      title: '4 de Bastos',
      imageSrc: 'img/wands04.jpg',
      description: `Cosecha en el hogar. Tiempo para celebrar las recompensas que han llegado. Pero aún hay más trabajo en el futuro.`,
      tags: ['bastos'],
    },
    {
      order: 5,
      title: '5 de Bastos',
      imageSrc: 'img/wands05.jpg',
      description: `Caos. Un montón de energía fluyendo en diferentes direcciones. Falta de organización.`,
      tags: ['bastos'],
    },
    {
      order: 6,
      title: '6 de Bastos',
      imageSrc: 'img/wands06.jpg',
      description: `La victoria sobre algo. Buena perspectiva. Frecuentemente victoria en un trabajo.`,
      tags: ['bastos'],
    },
    {
      order: 7,
      title: '7 de Bastos',
      imageSrc: 'img/wands07.jpg',
      description: `Posición y fuerza para tratar con la oposición. El consultante está en una posición más fuerte que la que pensaba originalmente.`,
      tags: ['bastos'],
    },
    {
      order: 8,
      title: '8 de Bastos',
      imageSrc: 'img/wands08.jpg',
      description: `Los obstáculos son quitados del camino. Rápido progreso. Es movimiento.`,
      tags: ['bastos'],
    },
    {
      order: 9,
      title: '9 de Bastos',
      imageSrc: 'img/wands09.jpg',
      description: `La lucha está más cerca al final de lo que uno piensa, pero aún hay energía y la lucha continuará si es necesario. Al consultante le puede parecer que la lucha no tiene fin.`,
      tags: ['bastos'],
    },
    {
      order: 10,
      title: '10 de Bastos',
      imageSrc: 'img/wands10.jpg',
      description: `La lucha se ha vuelto una carga. El consultante puede acostarse, pero puede estar reacio a dejar esta carga. Es como el artista que siente un impulso por continuar perfeccionando su trabajo, en lugar de buscar una forma de terminarlo o resolverlo.`,
      tags: ['bastos'],
    },
    {
      order: 11,
      title: 'Paje de Bastos',
      imageSrc: 'img/wands11.jpg',
      description: `Una persona energética. Podría ser también que ya vienen buenas noticias.`,
      tags: ['bastos'],
    },
    {
      order: 12,
      title: 'Caballero de Bastos',
      imageSrc: 'img/wands12.jpg',
      description: `Movimiento rápido, pero fácilmente desviado. Posible movimiento. Un buen amigo. En términos de movimiento, este Caballero es fácilmente desviado por otros intereses.`,
      tags: ['bastos'],
    },
    {
      order: 13,
      title: 'Reina de Bastos',
      imageSrc: 'img/wands13.jpg',
      description: `El amor de la vida. Tiene un montón de energía para sus propios intereses y los de su familia.`,
      tags: ['bastos'],
    },
    {
      order: 14,
      title: 'Rey de Bastos',
      imageSrc: 'img/wands14.jpg',
      description: `Encantador y amable. Capaz de ver el cuadro general pero no muy bien los detalles.`,
      tags: ['bastos'],
    },

    {
      order: 1,
      title: 'As de Espadas',
      imageSrc: 'img/swords01.jpg',
      description: `No sólo un comienzo, sino uno que se perfila como una victoria, o como
sobreponerse a algo.`,
      tags: ['espadas'],
    },
    {
      order: 2,
      title: '2 de Espadas',
      imageSrc: 'img/swords02.jpg',
      description: `Una decisión que tomar. Las emociones pueden nublar la situación y enceguecer al consultante.`,
      tags: ['espadas'],
    },
    {
      order: 3,
      title: '3 de Espadas',
      imageSrc: 'img/swords03.jpg',
      description: `Un tiempo de dificultad y dolor. Un corazón roto. Para algunos una mancha en el vestido plateado.`,
      tags: ['espadas'],
    },
    {
      order: 4,
      title: '4 de Espadas',
      imageSrc: 'img/swords04.jpg',
      description: `Aunque algunas piensan que esta carta está conectada con la muerte, señala tiempo de reposo y renovación, o un distanciamiento de la acción.`,
      tags: ['espadas'],
    },
    {
      order: 5,
      title: '5 de Espadas',
      imageSrc: 'img/swords05.jpg',
      description: `Rendición. La pelea está perdida. La victoria sólo llegará cediendo el control.`, tags: ['espadas'],
    },
    {
      order: 6,
      title: '6 de Espadas',
      imageSrc: 'img/swords06.jpg',
      description: `Avanzando de un tiempo difícil a uno mejor. Copas Buenas recompensas y alegría conectadas con una influencia del pasado.`,
      tags: ['espadas'],
    },
    {
      order: 7,
      title: '7 de Espadas',
      imageSrc: 'img/swords07.jpg',
      description: `Este es el ladrón. Puede que necesite una forma más discreta de enfrentar un desafío, en lugar de encararlo abiertamente, o puede ser una alerta de que alguien está tomando algo del consultante, o que el consultante está inadvertidamente tomando algo de alguien más.`,
      tags: ['espadas'],
    },
    {
      order: 8,
      title: '8 de Espadas',
      imageSrc: 'img/swords08.jpg',
      description: `El consultante ha creado una trampa de preocupaciones y miedos. Las palabras que bloquean el camino son pensamientos y preocupaciones de que no podrá resultar.`,
      tags: ['espadas'],
    },
    {
      order: 9,
      title: '9 de Espadas',
      imageSrc: 'img/swords09.jpg',
      description: `Preocupaciones y ansiedad, pero innecesarias, ya que las cosas resultarán. Las preocupaciones están causando un problema peor que el problema acerca del cual están preocupadas. Es la preocupación, ahora, la que podría traer el fracaso.`,
      tags: ['espadas'],
    },
    {
      order: 10,
      title: '10 de Espadas',
      imageSrc: 'img/swords10.jpg',
      description: `Muerte y fin. Un final oscuro, pero la luz seguirá.`,
      tags: ['espadas'],
    },
    {
      order: 11,
      title: 'Paje de Espadas',
      imageSrc: 'img/swords11.jpg',
      description: `Una persona inteligente, pero más preocupada en los hechos que en los sentimientos de la gente. Posiblemente un chismoso, desde que esta persona está más interesada en información que en las emociones y puede lastimar a la gente sin proponérselo.`,
      tags: ['espadas'],
    },
    {
      order: 12,
      title: 'Caballero de Espadas',
      imageSrc: 'img/swords12.jpg',
      description: `Movimiento rápido y progreso, frecuentemente hecho sin cuidado de estar hiriendo a otros. Usualmente este movimiento es tan rápido que, si no se es precavido o no es confrontado, dejará caos.`,
      tags: ['espadas'],
    },
    {
      order: 13,
      title: 'Reina de Espadas',
      imageSrc: 'img/swords13.jpg',
      description: `Un mujer fuerte, probablemente alguien que ha sufrido una pérdida reciente, pero lo suficientemente sabia para saber que la pérdida no es el fin y el amor vendrá otra vez.`,
      tags: ['espadas'],
    },
    {
      order: 14,
      title: 'Rey de Espadas',
      imageSrc: 'img/swords14.jpg',
      description: `Un hombre inteligente, que juzga en base a los hechos y las acciones, no a las
emociones.`,
      tags: ['espadas'],
    },

    {
      order: 1,
      title: 'As de Copas',
      imageSrc: 'img/cups01.jpg',
      description: `Un inicio emocional. Notar que es un UNO no un dos. Tiene que ver más con sólo el consultante que con una relación.`,
      tags: ['copas'],
    },
    {
      order: 2,
      title: '2 de Copas',
      imageSrc: 'img/cups02.jpg',
      description: `Relaciones, usualmente romance. Otras cartas alrededor pueden decir más acerca de la relación. Por sí mismo, es un buen signo para relaciones.`,
      tags: ['copas'],
    },
    {
      order: 3,
      title: '3 de Copas',
      imageSrc: 'img/cups03.jpg',
      description: `Tiempo para celebración y alegría, pero viene más trabajo por hacer.`,
      tags: ['copas'],
    },
    {
      order: 4,
      title: '4 de Copas',
      imageSrc: 'img/cups04.jpg',
      description: `Algo esta siendo ofrecido, pero la atención es tan fuerte sobre lo que ya está presente, que el nuevo regalo u ofrecimiento no será aceptado o apreciado por el momento.`,
      tags: ['copas'],
    },
    {
      order: 5,
      title: '5 de Copas',
      imageSrc: 'img/cups05.jpg',
      description: `En este punto es fácil ver lo negativo y las pérdidas en lugar de la buena fortuna que aún hay.`,
      tags: ['copas'],
    },
    {
      order: 6,
      title: '6 de Copas',
      imageSrc: 'img/cups06.jpg',
      description: `Buenas recompensas y alegría conectadas con una influencia del pasado.`,
      tags: ['copas'],
    },
    {
      order: 7,
      title: '7 de Copas',
      imageSrc: 'img/cups07.jpg',
      description: `Se presentan decisiones. Algunas son falsas, o ilusiones, o peligrosas. En este tiempo puede ser difícil distinguir por dónde ir, y puede ser mejor esperar hasta que la niebla se aclare.`,
      tags: ['copas'],
    },
    {
      order: 8,
      title: '8 de Copas',
      imageSrc: 'img/cups08.jpg',
      description: `Es tiempo de moverse en otra dirección. El consultante tiene estructuras que casi han sido acabadas y que no pueden servirle más para un propósito útil, y es tiempo de cambiar el ciclo.`,
      tags: ['copas'],
    },
    {
      order: 9,
      title: '9 de Copas',
      imageSrc: 'img/cups09.jpg',
      description: `La carta de los deseos. Los deseos se vuelven realidad. Pida algo.`,
      tags: ['copas'],
    },
    {
      order: 10,
      title: '10 de Copas',
      imageSrc: 'img/cups10.jpg',
      description: `Felicidad y alegría. Posiblemente en conexión con la familia. Final feliz.`,
      tags: ['copas'],
    },
    {
      order: 11,
      title: 'Paje de Copas',
      imageSrc: 'img/cups11.jpg',
      description: `Joven sensible, o un nuevo comienzo, o un nacimiento en la personalidad del consultante.`,
      tags: ['copas'],
    },
    {
      order: 12,
      title: 'Caballero de Copas',
      imageSrc: 'img/cups12.jpg',
      description: `Este Caballero es el consultante de las artes y la Verdad. También es el Caballero que sigue su propio corazón. Puede representar un interés romántico por alguien remoto o en el futuro, o un rival romántico.`,
      tags: ['copas'],
    },
    {
      order: 13,
      title: 'Reina de Copas',
      imageSrc: 'img/cups13.jpg',
      description: `Una mujer en armonía consigo misma. Probablemente tan en armonía que no siempre tiene conciencia de lo que le rodea.`,
      tags: ['copas'],
    },
    {
      order: 14,
      title: 'Rey de Copas',
      imageSrc: 'img/cups14.jpg',
      description: `Un hombre que ayuda a otros, pero probablemente no está en contacto consigo mismo.`,
      tags: ['copas'],
    },

    {
      order: 1,
      title: 'As de Oros',
      imageSrc: 'img/pents01.jpg',
      description: `Un nuevo ingreso o un nuevo trabajo. Algo con nuevo dinero o bienes materiales.
Muestra un fantástico tiempo para ir a buscar trabajo.`,
      tags: ['oros'],
    },
    {
      order: 2,
      title: '2 de Oros',
      imageSrc: 'img/pents02.jpg',
      description: `Acto de equilibrio. Será necesario para equilibrar diferentes situaciones, trabajos o fuentes de ingreso. Probable ganancia al final.`,
      tags: ['oros'],
    },
    {
      order: 3,
      title: '3 de Oros',
      imageSrc: 'img/pents03.jpg',
      description: `Tiempo de educación y aprendizaje. Algunos lectores ven en esta carta al maestro, pero parece muy prematura la maestría en este ciclo.`,
      tags: ['oros'],
    },
    {
      order: 4,
      title: '4 de Oros',
      imageSrc: 'img/pents04.jpg',
      description: `Es el avaro que se aferra tanto a su dinero que él no lo controla, sino el dinero a él.`,
      tags: ['oros'],
    },
    {
      order: 5,
      title: '5 de Oros',
      imageSrc: 'img/pents05.jpg',
      description: `Problemas que tiene que ver con la falta de fe u otras pérdidas. Depresión o pesar.`,
      tags: ['oros'],
    },
    {
      order: 6,
      title: '6 de Oros',
      imageSrc: 'img/pents06.jpg',
      description: `El dinero llegará, probablemente de una fuente improbable.`,
      tags: ['oros'],
    },
    {
      order: 7,
      title: '7 de Oros',
      imageSrc: 'img/pents07.jpg',
      description: `Trabajo duro que no parece que sea pagado. Es difícil ver los frutos del trabajo de uno.`,
      tags: ['oros'],
    },
    {
      order: 8,
      title: '8 de Oros',
      imageSrc: 'img/pents08.jpg',
      description: `Un hobby o pasatiempo agradable se convierte en un empleo provechoso. Probablemente empezará si muchos ingresos, pero el potencial para más está allí.`,
      tags: ['oros'],
    },
    {
      order: 9,
      title: '9 de Oros',
      imageSrc: 'img/pents09.jpg',
      description: `Comodidad y opulencia. Probablemente un tiempo de solitario disfrute. Una persona disfrutando por lo que ha trabajado y construido.`,
      tags: ['oros'],
    },
    {
      order: 10,
      title: '10 de Oros',
      imageSrc: 'img/pents10.jpg',
      description: `Buen tiempo para comprar o vender propiedades. Posible mudanza.`,
      tags: ['oros'],
    },
    {
      order: 11,
      title: 'Paje de Oros',
      imageSrc: 'img/pents11.jpg',
      description: `Oportunidad de negocios en la planta baja, o un joven trabajador y diligente.`,
      tags: ['oros'],
    },
    {
      order: 12,
      title: 'Caballero de Oros',
      imageSrc: 'img/pents12.jpg',
      description: `Lento pero en continuo progreso. Este progreso está asegurado. Se acercan buenas oportunidades financieras o de negocios.`,
      tags: ['oros'],
    },
    {
      order: 13,
      title: 'Reina de Oros',
      imageSrc: 'img/pents13.jpg',
      description: `Alguien trabajadora que ha ganado su opulencia, pero que también es generosa.`,
      tags: ['oros'],
    },
    {
      order: 14,
      title: 'Rey de Oros',
      imageSrc: 'img/pents14.jpg',
      description: `Un buen hombre de negocios. Alguien trabajador que ha ganado su opulencia, pero que también es generoso.`,
      tags: ['oros'],
    },
  ];

export default Deck;