const Deck = [
    {
      order: 0,
      title: 'El Loco',
      imageSrc: 'img/maj00.jpg',
      description: `Una persona inocente y buena al inicio de un viaje.`,
      tags: ['mayor'],
    },
    {
      order: 1,
      title: 'El Mago',
      imageSrc: 'img/maj01.jpg',
      description: `El maestro que lo presenta ante un potencial ilimitado.`,
      tags: ['mayor'],
    },
    {
      order: 2,
      title: 'La Sacerdotisa',
      imageSrc: 'img/maj02.jpg',
      description: `Ella es nuestra intuición, los misterios del espíritu.`,
      tags: ['mayor'],
    },
    {
      order: 3,
      title: 'La Emperatriz',
      imageSrc: 'img/maj03.jpg',
      description: `Representa la creatividad, la fertilidad y a la Naturaleza.`,
      tags: ['mayor'],
    },
    {
      order: 4,
      title: 'El Emperador',
      imageSrc: 'img/maj04.jpg',
      description: `Representa el poder, la estructura y el control.`,
      tags: ['mayor'],
    },
    {
      order: 5,
      title: 'El Sacerdote',
      imageSrc: 'img/maj05.jpg',
      description: `La estructura religiosa tradicional, el guía espiritual.`,
      tags: ['mayor'],
    },
    {
      order: 6,
      title: 'Los Amantes',
      imageSrc: 'img/maj06.jpg',
      description: `Lecciones de amor, incluyendo el amor a sí mismo.`,
      tags: ['mayor'],
    },
    {
      order: 7,
      title: 'El Carro',
      imageSrc: 'img/maj07.jpg',
      description: `Conflictos o decisiones. Posible viaje.`,
      tags: ['mayor'],
    },
    {
      order: 8,
      title: 'La Fuerza',
      imageSrc: 'img/maj08.jpg',
      description: `La fuerza que necesitamos para enfrentar a los problemas de la vida.`,
      tags: ['mayor'],
    },
    {
      order: 9,
      title: 'El Ermitaño',
      imageSrc: 'img/maj09.jpg',
      description: `La solitaria búsqueda de la Verdad.`,
      tags: ['mayor'],
    },
    {
      order: 10,
      title: 'La Rueda de la Fortuna',
      imageSrc: 'img/maj10.jpg',
      description: `Un cambio de suerte como el giro de una rueda.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'La Justicia',
      imageSrc: 'img/maj11.jpg',
      description: `La capacidad de considerar los hechos y realizar buenos juicios.`,
      tags: ['mayor'],
    },
    {
      order: 12,
      title: 'El Ahorcado',
      imageSrc: 'img/maj12.jpg',
      description: `Sacrificio de partes propias para un bien mayor.`,
      tags: ['mayor'],
    },
    {
      order: 13,
      title: 'La Muerte',
      imageSrc: 'img/maj13.jpg',
      description: `Un final o cambio, muerte metafórica.`,
      tags: ['mayor'],
    },
    {
      order: 14,
      title: 'La Tolerancia',
      imageSrc: 'img/maj14.jpg',
      description: `Balance interno o emocional.`,
      tags: ['mayor'],
    },
    {
      order: 15,
      title: 'El Demonio',
      imageSrc: 'img/maj15.jpg',
      description: `El infierno y el sufrimiento que creamos en nuestra vida.`,
      tags: ['mayor'],
    },
    {
      order: 16,
      title: 'La Torre',
      imageSrc: 'img/maj16.jpg',
      description: `Destrucción de una estructura en la vida.`,
      tags: ['mayor'],
    },
    {
      order: 17,
      title: 'La Estrella',
      imageSrc: 'img/maj17.jpg',
      description: `El regalo de nuestro propio destino.`,
      tags: ['mayor'],
    },
    {
      order: 18,
      title: 'La Luna',
      imageSrc: 'img/maj18.jpg',
      description: `Ilusión o lo que no vemos.`,
      tags: ['mayor'],
    },
    {
      order: 19,
      title: 'El Sol',
      imageSrc: 'img/maj19.jpg',
      description: `Alegría y brillo y prosperidad.`,
      tags: ['mayor'],
    },
    {
      order: 20,
      title: 'El Juicio',
      imageSrc: 'img/maj20.jpg',
      description: `Pago de viejas deudas para un nuevo inicio.`,
      tags: ['mayor'],
    },
    {
      order: 21,
      title: 'El Mundo',
      imageSrc: 'img/maj21.jpg',
      description: `Un círculo que representa que el ciclo está completo.`,
      tags: ['mayor'],
    },

    {
      order: 1,
      title: 'As de Bastos',
      imageSrc: 'img/wands01.jpg',
      description: `El inicio de un nuevo proyecto creativo o energía creativa que empieza a ser llevada hacia otro proyecto.`,
      tags: ['bastos'],
    },
    {
      order: 2,
      title: '2 de Bastos',
      imageSrc: 'img/wands02.jpg',
      description: `Energía creativa que sólo busca ser liberada para traer buenos resultados.`,
      tags: ['bastos'],
    },
    {
      order: 3,
      title: '3 de Bastos',
      imageSrc: 'img/wands03.jpg',
      description: `Buenos resultados de la energía que invirtió, que vendrá de regreso de una manera positiva.`,
      tags: ['bastos'],
    },
    {
      order: 4,
      title: '4 de Bastos',
      imageSrc: 'img/wands04.jpg',
      description: `Cosecha en el hogar. Tiempo para celebrar las recompensas que han llegado. Pero aún hay más trabajo en el futuro.`,
      tags: ['bastos'],
    },
    {
      order: 5,
      title: '5 de Bastos',
      imageSrc: 'img/wands05.jpg',
      description: `Caos. Un montón de energía fluyendo en diferentes direcciones. Falta de organización.`,
      tags: ['bastos'],
    },
    {
      order: 6,
      title: '6 de Bastos',
      imageSrc: 'img/wands06.jpg',
      description: `La victoria sobre algo. Buena perspectiva. Frecuentemente victoria en un trabajo.`,
      tags: ['bastos'],
    },
    {
      order: 7,
      title: '7 de Bastos',
      imageSrc: 'img/wands07.jpg',
      description: `Posición y fuerza para tratar con la oposición. El consultante está en una posición más fuerte que la que pensaba originalmente.`,
      tags: ['bastos'],
    },
    {
      order: 8,
      title: '8 de Bastos',
      imageSrc: 'img/wands08.jpg',
      description: `Los obstáculos son quitados del camino. Rápido progreso. Es movimiento.`,
      tags: ['bastos'],
    },
    {
      order: 9,
      title: '9 de Bastos',
      imageSrc: 'img/wands09.jpg',
      description: `La lucha está más cerca al final de lo que uno piensa, pero aún hay energía y la lucha continuará si es necesario. Al consultante le puede parecer que la lucha no tiene fin.`,
      tags: ['bastos'],
    },
    {
      order: 10,
      title: '10 de Bastos',
      imageSrc: 'img/wands10.jpg',
      description: `La lucha se ha vuelto una carga. El consultante puede acostarse, pero puede estar reacio a dejar esta carga. Es como el artista que siente un impulso por continuar perfeccionando su trabajo, en lugar de buscar una forma de terminarlo o resolverlo.`,
      tags: ['bastos'],
    },
    {
      order: 11,
      title: 'Paje de Bastos',
      imageSrc: 'img/wands11.jpg',
      description: `Una persona energética. Podría ser también que ya vienen buenas noticias.`,
      tags: ['bastos'],
    },
    {
      order: 12,
      title: 'Caballero de Bastos',
      imageSrc: 'img/wands12.jpg',
      description: `Movimiento rápido, pero fácilmente desviado. Posible movimiento. Un buen amigo. En términos de movimiento, este Caballero es fácilmente desviado por otros intereses.`,
      tags: ['bastos'],
    },
    {
      order: 13,
      title: 'Reina de Bastos',
      imageSrc: 'img/wands13.jpg',
      description: `El amor de la vida. Tiene un montón de energía para sus propios intereses y los de su familia.`,
      tags: ['bastos'],
    },
    {
      order: 14,
      title: 'Rey de Bastos',
      imageSrc: 'img/wands14.jpg',
      description: `Encantador y amable. Capaz de ver el cuadro general pero no muy bien los detalles.`,
      tags: ['bastos'],
    },

    {
      order: 1,
      title: 'As de Espadas',
      imageSrc: 'img/swords01.jpg',
      description: `No sólo un comienzo, sino uno que se perfila como una victoria, o como
sobreponerse a algo.`,
      tags: ['espadas'],
    },
    {
      order: 2,
      title: '2 de Espadas',
      imageSrc: 'img/swords02.jpg',
      description: `Energía creativa que sólo busca ser liberada para traer buenos resultados.`,
      tags: ['bastos'],
    },
    {
      order: 3,
      title: '3 de Espadas',
      imageSrc: 'img/swords03.jpg',
      description: `Buenos resultados de la energía que invirtió, que vendrá de regreso de una manera positiva.`,
      tags: ['bastos'],
    },
    {
      order: 4,
      title: '4 de Espadas',
      imageSrc: 'img/swords04.jpg',
      description: `Cosecha en el hogar. Tiempo para celebrar las recompensas que han llegado. Pero aún hay más trabajo en el futuro.`,
      tags: ['bastos'],
    },
    {
      order: 5,
      title: '5 de Espadas',
      imageSrc: 'img/swords05.jpg',
      description: `Caos. Un montón de energía fluyendo en diferentes direcciones. Falta de organización.`,
      tags: ['bastos'],
    },
    {
      order: 6,
      title: '6 de Espadas',
      imageSrc: 'img/swords06.jpg',
      description: `La victoria sobre algo. Buena perspectiva. Frecuentemente victoria en un trabajo.`,
      tags: ['bastos'],
    },
    {
      order: 7,
      title: '7 de Espadas',
      imageSrc: 'img/swords07.jpg',
      description: `Posición y fuerza para tratar con la oposición. El consultante está en una posición más fuerte que la que pensaba originalmente.`,
      tags: ['bastos'],
    },
    {
      order: 8,
      title: '8 de Espadas',
      imageSrc: 'img/swords08.jpg',
      description: `Los obstáculos son quitados del camino. Rápido progreso. Es movimiento.`,
      tags: ['bastos'],
    },
    {
      order: 9,
      title: '9 de Espadas',
      imageSrc: 'img/swords09.jpg',
      description: `La lucha está más cerca al final de lo que uno piensa, pero aún hay energía y la lucha continuará si es necesario. Al consultante le puede parecer que la lucha no tiene fin.`,
      tags: ['bastos'],
    },
    {
      order: 10,
      title: '10 de Espadas',
      imageSrc: 'img/swords10.jpg',
      description: `La lucha se ha vuelto una carga. El consultante puede acostarse, pero puede estar reacio a dejar esta carga. Es como el artista que siente un impulso por continuar perfeccionando su trabajo, en lugar de buscar una forma de terminarlo o resolverlo.`,
      tags: ['bastos'],
    },
    {
      order: 11,
      title: 'Paje de Espadas',
      imageSrc: 'img/swords11.jpg',
      description: `Una persona energética. Podría ser también que ya vienen buenas noticias.`,
      tags: ['bastos'],
    },
    {
      order: 12,
      title: 'Caballero de Espadas',
      imageSrc: 'img/swords12.jpg',
      description: `Movimiento rápido, pero fácilmente desviado. Posible movimiento. Un buen amigo. En términos de movimiento, este Caballero es fácilmente desviado por otros intereses.`,
      tags: ['bastos'],
    },
    {
      order: 13,
      title: 'Reina de Espadas',
      imageSrc: 'img/swords13.jpg',
      description: `El amor de la vida. Tiene un montón de energía para sus propios intereses y los de su familia.`,
      tags: ['bastos'],
    },
    {
      order: 14,
      title: 'Rey de Espadas',
      imageSrc: 'img/swords14.jpg',
      description: `Encantador y amable. Capaz de ver el cuadro general pero no muy bien los detalles.`,
      tags: ['bastos'],
    },

    {
      order: 1,
      title: 'As de Copas',
      imageSrc: 'img/cups01.jpg',
      description: `Un inicio emocional. Notar que es un UNO no un dos. Tiene que ver más con sólo el consultante que con una relación.`,
      tags: ['copas'],
    },
    {
      order: 2,
      title: '2 de Copas',
      imageSrc: 'img/cups02.jpg',
      description: `Energía creativa que sólo busca ser liberada para traer buenos resultados.`,
      tags: ['bastos'],
    },
    {
      order: 3,
      title: '3 de Copas',
      imageSrc: 'img/cups03.jpg',
      description: `Buenos resultados de la energía que invirtió, que vendrá de regreso de una manera positiva.`,
      tags: ['bastos'],
    },
    {
      order: 4,
      title: '4 de Copas',
      imageSrc: 'img/cups04.jpg',
      description: `Cosecha en el hogar. Tiempo para celebrar las recompensas que han llegado. Pero aún hay más trabajo en el futuro.`,
      tags: ['bastos'],
    },
    {
      order: 5,
      title: '5 de Copas',
      imageSrc: 'img/cups05.jpg',
      description: `Caos. Un montón de energía fluyendo en diferentes direcciones. Falta de organización.`,
      tags: ['bastos'],
    },
    {
      order: 6,
      title: '6 de Copas',
      imageSrc: 'img/cups06.jpg',
      description: `La victoria sobre algo. Buena perspectiva. Frecuentemente victoria en un trabajo.`,
      tags: ['bastos'],
    },
    {
      order: 7,
      title: '7 de Copas',
      imageSrc: 'img/cups07.jpg',
      description: `Posición y fuerza para tratar con la oposición. El consultante está en una posición más fuerte que la que pensaba originalmente.`,
      tags: ['bastos'],
    },
    {
      order: 8,
      title: '8 de Copas',
      imageSrc: 'img/cups08.jpg',
      description: `Los obstáculos son quitados del camino. Rápido progreso. Es movimiento.`,
      tags: ['bastos'],
    },
    {
      order: 9,
      title: '9 de Copas',
      imageSrc: 'img/cups09.jpg',
      description: `La lucha está más cerca al final de lo que uno piensa, pero aún hay energía y la lucha continuará si es necesario. Al consultante le puede parecer que la lucha no tiene fin.`,
      tags: ['bastos'],
    },
    {
      order: 10,
      title: '10 de Copas',
      imageSrc: 'img/cups10.jpg',
      description: `La lucha se ha vuelto una carga. El consultante puede acostarse, pero puede estar reacio a dejar esta carga. Es como el artista que siente un impulso por continuar perfeccionando su trabajo, en lugar de buscar una forma de terminarlo o resolverlo.`,
      tags: ['bastos'],
    },
    {
      order: 11,
      title: 'Paje de Copas',
      imageSrc: 'img/cups11.jpg',
      description: `Una persona energética. Podría ser también que ya vienen buenas noticias.`,
      tags: ['bastos'],
    },
    {
      order: 12,
      title: 'Caballero de Copas',
      imageSrc: 'img/cups12.jpg',
      description: `Movimiento rápido, pero fácilmente desviado. Posible movimiento. Un buen amigo. En términos de movimiento, este Caballero es fácilmente desviado por otros intereses.`,
      tags: ['bastos'],
    },
    {
      order: 13,
      title: 'Reina de Copas',
      imageSrc: 'img/cups13.jpg',
      description: `El amor de la vida. Tiene un montón de energía para sus propios intereses y los de su familia.`,
      tags: ['bastos'],
    },
    {
      order: 14,
      title: 'Rey de Copas',
      imageSrc: 'img/cups14.jpg',
      description: `Encantador y amable. Capaz de ver el cuadro general pero no muy bien los detalles.`,
      tags: ['bastos'],
    },

    {
      order: 1,
      title: 'As de Oros',
      imageSrc: 'img/pents01.jpg',
      description: `Un nuevo ingreso o un nuevo trabajo. Algo con nuevo dinero o bienes materiales.
Muestra un fantástico tiempo para ir a buscar trabajo.`,
      tags: ['oros'],
    },
    {
      order: 2,
      title: '2 de Oros',
      imageSrc: 'img/pents02.jpg',
      description: `Energía creativa que sólo busca ser liberada para traer buenos resultados.`,
      tags: ['bastos'],
    },
    {
      order: 3,
      title: '3 de Oros',
      imageSrc: 'img/pents03.jpg',
      description: `Buenos resultados de la energía que invirtió, que vendrá de regreso de una manera positiva.`,
      tags: ['bastos'],
    },
    {
      order: 4,
      title: '4 de Oros',
      imageSrc: 'img/pents04.jpg',
      description: `Cosecha en el hogar. Tiempo para celebrar las recompensas que han llegado. Pero aún hay más trabajo en el futuro.`,
      tags: ['bastos'],
    },
    {
      order: 5,
      title: '5 de Oros',
      imageSrc: 'img/pents05.jpg',
      description: `Caos. Un montón de energía fluyendo en diferentes direcciones. Falta de organización.`,
      tags: ['bastos'],
    },
    {
      order: 6,
      title: '6 de Oros',
      imageSrc: 'img/pents06.jpg',
      description: `La victoria sobre algo. Buena perspectiva. Frecuentemente victoria en un trabajo.`,
      tags: ['bastos'],
    },
    {
      order: 7,
      title: '7 de Oros',
      imageSrc: 'img/pents07.jpg',
      description: `Posición y fuerza para tratar con la oposición. El consultante está en una posición más fuerte que la que pensaba originalmente.`,
      tags: ['bastos'],
    },
    {
      order: 8,
      title: '8 de Oros',
      imageSrc: 'img/pents08.jpg',
      description: `Los obstáculos son quitados del camino. Rápido progreso. Es movimiento.`,
      tags: ['bastos'],
    },
    {
      order: 9,
      title: '9 de Oros',
      imageSrc: 'img/pents09.jpg',
      description: `La lucha está más cerca al final de lo que uno piensa, pero aún hay energía y la lucha continuará si es necesario. Al consultante le puede parecer que la lucha no tiene fin.`,
      tags: ['bastos'],
    },
    {
      order: 10,
      title: '10 de Oros',
      imageSrc: 'img/pents10.jpg',
      description: `La lucha se ha vuelto una carga. El consultante puede acostarse, pero puede estar reacio a dejar esta carga. Es como el artista que siente un impulso por continuar perfeccionando su trabajo, en lugar de buscar una forma de terminarlo o resolverlo.`,
      tags: ['bastos'],
    },
    {
      order: 11,
      title: 'Paje de Oros',
      imageSrc: 'img/pents11.jpg',
      description: `Una persona energética. Podría ser también que ya vienen buenas noticias.`,
      tags: ['bastos'],
    },
    {
      order: 12,
      title: 'Caballero de Oros',
      imageSrc: 'img/pents12.jpg',
      description: `Movimiento rápido, pero fácilmente desviado. Posible movimiento. Un buen amigo. En términos de movimiento, este Caballero es fácilmente desviado por otros intereses.`,
      tags: ['bastos'],
    },
    {
      order: 13,
      title: 'Reina de Oros',
      imageSrc: 'img/pents13.jpg',
      description: `El amor de la vida. Tiene un montón de energía para sus propios intereses y los de su familia.`,
      tags: ['bastos'],
    },
    {
      order: 14,
      title: 'Rey de Oros',
      imageSrc: 'img/pents14.jpg',
      description: `Encantador y amable. Capaz de ver el cuadro general pero no muy bien los detalles.`,
      tags: ['bastos'],
    },
  ];

export default Deck;